CREATE TABLE Countries(Countrycode varchar(32), Countryname varchar(32));

INSERT INTO Countries(Countrycode,Countryname) VALUES ('ae','United Arab Emirates');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('af','Afghanistan');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('am','Armenia');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('ao','Angola');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('ar','Argentina');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('at','Austria');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('au','Australia');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('az','Azerbaijan');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('bd','Bangladesh');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('be','Belgium');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('bf','Burkina Faso');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('bg','Bulgaria');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('br','Brazil');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('by','Belarus');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('ca','Canada');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('cd','Democratic Republic of the Congo');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('cg','Republic of the Congo');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('ci','Ivory Coast');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('cl','Chile');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('cm','Cameroon');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('cn','China');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('co','Colombia');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('cz','Czech Republic');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('de','Germany');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('dk','Denmark');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('do','Dominican Republic');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('dz','Algeria');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('ec','Ecuador');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('eg','Egypt');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('es','Spain');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('et','Ethiopia');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('fr','France');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('gb','Great Britan');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('ge','Georgia');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('gh','Ghana');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('gn','Guinea');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('ht','Haiti');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('hu','Hungary');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('id','Indonesia');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('ie','Ireland');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('in','India');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('iq','Iraq');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('ir','Iran');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('it','Italy');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('jp','Japan');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('ke','Kenya');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('kh','Cambodia');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('kr','South Korea');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('kz','Kazakhstan');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('lb','Libanon');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('ly','Libya');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('ma','Marocco');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('mg','Madagascar');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('ml','Mali');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('mm','Myanmar');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('mx','Mexico');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('my','Malaysia');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('mz','Mozambique');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('ng','Nigeria');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('ni','Nicaragua');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('pe','Peru');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('ph','Philipines');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('pk','Pakistan');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('pl','Poland');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('ro','Romania');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('rs','Serbia');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('ru','Russia');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('sa','Saudi Arabia');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('sd','Sudan');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('se','Sweden');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('sg','Singapore');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('sl','Sierra Leone');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('sn','Senegal');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('so','Somalia');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('sy','Syria');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('th','Thailand');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('tr','Turkey');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('tw','Taiwan');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('tz','Tanzania');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('ua','Ukraine');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('ug','Uganda');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('us','United States of America');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('uy','Uruguay');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('uz','Uzbekistan');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('ve','Venezuela');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('vn','Vietnam');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('za','South Africa');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('zm','Zambia');
INSERT INTO Countries(Countrycode,Countryname) VALUES ('zw','Zimbabwe');
